name: ci
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - 'docs'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - 'docs'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Configure Environment
        run: |
          cp .env.ci .env

      - name: Cache Composer
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Composer Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --optimize-autoloader
          php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Sqlite Database
        run: php artisan make:sqlite

      - name: Run PHP Analysis
        run: composer lint

      - name: Run PHP Tests
        run: composer test-unit

      # Cant get Laravel Dusk to Work :(
      #- name: Cache NPM
      #  uses: actions/cache@v1
      #  with:
      #    path: node_modules
      #    key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      #- name: Install Node
      #  uses: actions/setup-node@v1
      #  with:
      #    node-version: 12.x

      #- name: Install Assets
      #  run: npm install --quiet --no-optional --prefer-offline --no-audit

      #- name: Compile Assets
      #  run: npm run production

      - name: Install Chrome Driver
        run: php artisan dusk:chrome-driver

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &

      - name: Serve Application
        run: php artisan serve > /dev/null 2>&1 &

      - name: Run Feature Tests
        env:
          #DB_CONNECTION: sqlite
          #DB_DATABASE: database/database.sqlite
          APP_URL: http://127.0.0.1:8000
          DUSK_CHROME_URL: http://localhost:9515
        run: php artisan dusk  --stop-on-failure

      - name: Store Log Artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Logs
          path: ./storage/logs

      - name: Store Screenshot Artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Screenshots
          path: ./tests/Browser/screenshots
